// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    Auth: {
        identityPoolId: 'ap-northeast-2:7e03ccd3-9a63-4ffb-921f-d4092b2d0bb1',
        region: 'ap-northeast-2',
        identityPoolRegion: 'ap-northeast-2',
        userPoolId: 'ap-northeast-2_IrjQknmdR',
        userPoolWebClientId: '5g2koa727ptabb5l0epddmas1q',

        cookieStorage: {
            // REQUIRED - Cookie domain (only required if cookieStorage is provided)
            domain: 'localhost',
            // OPTIONAL - Cookie path
            path: '/',
            // OPTIONAL - Cookie expiration in days
            expires: 7,
            // OPTIONAL - Cookie secure flag
            // Either true or false, indicating if the cookie transmission requires a secure protocol (https).
            secure: false
        }
    },
    API: {
        endpoints: [
            {
                name: "lotto",
                endpoint: "https://gg0v4lri81.execute-api.ap-northeast-2.amazonaws.com/dev",
                region: "ap-northeast-2",
            }
        ]
    }
}

export default awsconfig;
